"""empty message

Revision ID: 0838b63a78a9
Revises: 
Create Date: 2021-06-06 01:06:56.315465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0838b63a78a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('isCorrect', sa.Boolean(), nullable=True),
    sa.Column('option', sa.String(length=500), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('statement', sa.ARRAY(sa.String(length=20000)), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String(length=2000)), nullable=True),
    sa.Column('statement_types', sa.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('options_types', sa.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('answer', sa.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('isDifficult', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isExplained', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_array', sa.ARRAY(sa.String(length=20000)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('statement')
    op.drop_table('answers')
    # ### end Alembic commands ###
