"""empty message

Revision ID: 8b83e75a5760
Revises: 
Create Date: 2021-09-03 01:53:04.453905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b83e75a5760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('security_code', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin_of_everything', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('option', sa.String(length=500), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('statement', sa.ARRAY(sa.String(length=20000)), nullable=False),
    sa.Column('options', sa.ARRAY(sa.String(length=2000)), nullable=False),
    sa.Column('statement_types', sa.ARRAY(sa.String(length=150)), nullable=False),
    sa.Column('options_types', sa.ARRAY(sa.String(length=150)), nullable=False),
    sa.Column('answer', sa.ARRAY(sa.String(length=150)), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('is_difficult', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_explained', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('modified_by', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_creation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('statement', sa.ARRAY(sa.String(length=20000)), nullable=True),
    sa.Column('options', sa.ARRAY(sa.String(length=2000)), nullable=True),
    sa.Column('statement_types', sa.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('options_types', sa.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('answer', sa.ARRAY(sa.String(length=150)), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('is_difficult', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_explained', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('modified_by', sa.String(length=120), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_array', sa.ARRAY(sa.String(length=20000)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('highschool_score', sa.Integer(), nullable=True),
    sa.Column('cut_UCR', sa.Integer(), nullable=True),
    sa.Column('cut_UNA', sa.Integer(), nullable=True),
    sa.Column('cut_TEC', sa.Integer(), nullable=True),
    sa.Column('cut_GBL', sa.Integer(), nullable=True),
    sa.Column('is_UCR', sa.Boolean(), nullable=True),
    sa.Column('is_TEC', sa.Boolean(), nullable=True),
    sa.Column('is_UNA', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_problematic', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_statement', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.Column('show_to_all_admins', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('user')
    op.drop_table('test')
    op.drop_table('statement_creation')
    op.drop_table('statement')
    op.drop_table('answers')
    op.drop_table('administrator')
    # ### end Alembic commands ###
